// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderMyFood.Services.OrderApi.Data;

namespace OrderApi.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20210129131507_IdentityRemove")]
    partial class IdentityRemove
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderMyFood.Services.OrderApi.Model.Order", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("CustomerId");

                    b.Property<bool>("IsPaid");

                    b.Property<string>("Note");

                    b.Property<DateTime>("OrderCreated");

                    b.Property<double>("Price");

                    b.Property<int>("RestaurantId");

                    b.Property<int>("StatusId");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderMyFood.Services.OrderApi.Model.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MenuId");

                    b.Property<int>("OrderId");

                    b.Property<int>("Quantity");

                    b.HasKey("OrderDetailsId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("OrderMyFood.Services.OrderApi.Model.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new { StatusId = 1, StatusName = "Ordering" },
                        new { StatusId = 2, StatusName = "Preparing" },
                        new { StatusId = 3, StatusName = "Checking" },
                        new { StatusId = 4, StatusName = "Prepared" },
                        new { StatusId = 5, StatusName = "Delivered" },
                        new { StatusId = 6, StatusName = "Cancelled" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
